# Project information
site_name: Openterface | 打开无限可能的桥梁
site_url: https://cn.openterface.com/
site_author: Billy Wang
site_description: 功能丰富、开源且社区驱动的 KVM-over-USB 解决方案

# Repository
repo_name: Openterface
repo_url: https://github.com/TechxArtisanStudio/Openterface

# Copyright
copyright: >-
  Copyright &copy; All rights reserved. 2023 <a href="https://www.openterface.com">Openterface</a> | <a href="https://www.techxartisan.com">TechxArtisan</a> | Guangzhou Billio Tech. Co., Ltd. <br>
  <a href="">Home</a> |
  <a href="/terms-of-service">Terms of Service</a> |
  <a href="/privacy-policy">Privacy Policy</a> | 
  <a href="#__consent">Cookie Settings</a> | 
  <a href="/contact">Contact Us</a>

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: zh
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/app-logo.png
  favicon: images/favicon.png
  features:
   - navigation.tabs
   - navigation.sections
   - navigation.top
   - navigation.footer
   - navigation.indexes
   - toc.integrate
   - search.suggest
   - search.highlight
   - content.tabs
   - content.code.annotation
   - content.code.copy
   - content.tabs.link

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra:
  social:
    - icon: txa/crowd-supply-icon
      link: https://www.crowdsupply.com/techxartisan/openterface-mini-kvm
    - icon: fontawesome/brands/reddit-alien
      link: /reddit
    - icon: fontawesome/brands/discord
      link: /discord
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@TechxArtisan
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/TechxArtisan
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/TechxArtisan
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/techxartisan/
  
  alternate:
    - name: English
      link: /
      lang: en
    - name: 日本語
      link: https://jp.openterface.com/
      lang: ja
    - name: 한국어
      link: https://kr.openterface.com/
      lang: ko
    - name: Français
      link: https://fr.openterface.com/
      lang: fr
    - name: Deutsch
      link: https://de.openterface.com/
      lang: de
    - name: Italiano
      link: https://it.openterface.com/
      lang: it
    - name: Español
      link: https://es.openterface.com/
      lang: es
    - name: Português
      link: https://pt.openterface.com/
      lang: pt
    - name: Română
      link: https://ro.openterface.com/
      lang: ro
    - name: 简体中文
      link: https://cn.openterface.com/
      lang: zh
    # - name: Svenska
    #   link: https://sv.openterface.com/
    #   lang: sv
    # - name: Polski
    #   link: https://pl.openterface.com/
    #   lang: pl
    # - name: Nederlands
    #   link: https://nl.openterface.com/
    #   lang: nl
    
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to enhance quality of docs content, analyse site effectiveness and needs. 
      By consenting, you help us improve our website. Thanks!
    actions:
      - accept
      - reject
  analytics:
    provider: google
    property: G-EKZEH6QYWT

markdown_extensions:
  # Enables tables
  - tables
  # Enables admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
              custom_icons:
                - overrides/.icons
  - toc:
      permalink: ¶
      toc_depth: 3

plugins:
  - glightbox
  - search
  - redirects:
      redirect_maps:
        'basic-testing.md': 'basic.md'
        'community.md': 'https://www.reddit.com/r/Openterface_miniKVM/'
        'discord.md': 'https://discord.gg/sFTJD6a3R8'
        'reddit.md': 'https://www.reddit.com/r/Openterface_miniKVM/'
        'macos.md': 'https://github.com/TechxArtisanStudio/Openterface_MacOS'
        'android.md': 'https://github.com/TechxArtisanStudio/Openterface_Android'
        'qt.md': 'https://github.com/TechxArtisanStudio/Openterface_QT'
        'window.md': 'https://github.com/TechxArtisanStudio/Openterface_QT'
        'linux.md': 'https://github.com/TechxArtisanStudio/Openterface_QT'
        'hardware.md': 'https://github.com/TechxArtisanStudio/Openterface_Mini-KVM_Hardware'
        'feedback.md': 'https://forms.gle/YJLrCKwro8tbi6ar7'
        'oshw.md': 'https://certification.oshwa.org/cn000015.html'
        'x.md': 'https://x.com/TechxArtisan'
  - tags:
      tags_file: tags.md
  - blog:
      post_url_format: "{slug}"
      authors_file: "{blog}/.authors.yml"
      blog_toc: true
      post_excerpt_separator: <!-- more -->
      categories_name: Categories
      categories_toc: true
      pagination: true
      pagination_per_page: 10
      draft: true
      archive: false

nav:
  - 首页: index.md
  - 文档:
    - 快速开始: quick-start.md
    - 功能特点: features.md
    - 如何连接: how-to-connect.md
    - 开源软件: app.md
    - 开源硬件: open-hardware.md
    - 基本控制: basic.md
    - 可切换USB端口: usb-switch.md
    - 扩展引脚: pin.md
    - 使用案例: use-cases.md
    - 规格参数: specifications.md
    - 包装内容: whats-in-the-box.md
    - 配件: accessories.md
    - 工作原理: how-it-works.md
    - 为什么选择Openterface: why-openterface.md
    - 对比: comparison.md
    - 常见问题: faq.md
    - 开发:
      - 测试与开发: test.md
      - 路线图: roadmap.md
      - 贡献: contributing.md
  - 常见问题: /faq
  - 使用案例: /use-cases
  - 博客:
    - blog/index.md
  - Reddit: /reddit
  - Discord: /discord
  - 关于:
    - 联系我们: contact.md
    - 政策:
      - 隐私政策: privacy-policy.md
      - 服务条款: terms-of-service.md
      - 退货、退款与保修: return-refunds-warranty.md