// AUTO-GENERATED by scripts/sync-home-videos.mjs — do not edit manually
// locale: zh | generated: 2026-06-22T12:45:02.717Z

import type { HomeVideo } from '../lib/youtube';

export const homeVideosLocale = 'zh' as const;

/** Top 10 videos for homepage strip (duplicated for seamless scroll). */
export const homeVideos: HomeVideo[] = [
  {
    "url": "https://www.youtube.com/watch?v=URAXtrB817E",
    "title": "KVM-GO OpenInterface: Este KVM NO va por red, el KVM que se conecta DIRECTO a tu PC",
    "author": "Javier Gutierrez Abella",
    "channelAvatar": "https://yt3.ggpht.com/ytc/AIdro_lkVDRCHKSbjko5n0Vto1FazyoHLtYHZ0BJLq554iF0ZNW1=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/URAXtrB817E/hqdefault.jpg",
    "date": "2026-03-20",
    "views": 9549,
    "viewsFormatted": "9.5K"
  },
  {
    "url": "https://www.youtube.com/watch?v=JK4XaMo8yEI",
    "title": "A USB KVM with VGA! Openterface KVM-GO Review",
    "author": "apalrd's adventures",
    "channelAvatar": "https://yt3.ggpht.com/qencJ8YC4SCPbV_ylp47d-yNIAMTzt6QlncVrJ8FfwRDYeB4m7St7MZNSCDOVx3Qw_9CJxHR5A=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/JK4XaMo8yEI/hqdefault.jpg",
    "date": "2026-02-26",
    "views": 7828,
    "viewsFormatted": "7.8K"
  },
  {
    "url": "https://www.youtube.com/watch?v=BHRGIE8OGYY",
    "title": "Networkless KVM? Yes please open interface kvm-go",
    "author": "KL Tech Videos",
    "channelAvatar": "https://yt3.ggpht.com/mHmleJwkNJwBHMDRv-JXOxpitAiPG5YIsQ4uDApdTKjWu5mD_sUTfnH8VsL9Zwfcg5PKivTQ7Q=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/BHRGIE8OGYY/hqdefault.jpg",
    "date": "2025-12-31",
    "views": 717,
    "viewsFormatted": "717"
  },
  {
    "url": "https://www.youtube.com/watch?v=d9-i7SYAZr8",
    "title": "The KVM-GO is my new EDC KVM!",
    "author": "Symbiiote",
    "channelAvatar": "https://yt3.ggpht.com/OYi4mIbKHArwGmdur42okpmZ3VMRJlMixLH2YOvgv2EqWzzvxx1wgwh0RugCBjTuYAVGne4B=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/d9-i7SYAZr8/hqdefault.jpg",
    "date": "2025-12-29",
    "views": 1505,
    "viewsFormatted": "1.5K"
  },
  {
    "url": "https://www.youtube.com/watch?v=aXQSNFAFiqk",
    "title": "J’ai testé le KVM le plus compact au monde : OpenTerface KVM Go !",
    "author": "Sam's eXperiments logs",
    "channelAvatar": "https://yt3.ggpht.com/QypC0fMJdJDxdf_04lp6TWkuorFPB9pVZD8oOLwclsvRfJsfzCz01iaSl56A1J9lcCHUHXEM=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/aXQSNFAFiqk/hqdefault.jpg",
    "date": "2025-12-16",
    "views": 357,
    "viewsFormatted": "357"
  },
  {
    "url": "https://www.youtube.com/watch?v=__WfaaAS0O4",
    "title": "OpenInterface Shows New KVM Go at Maker Faire Shenzhen",
    "author": "Electromaker",
    "channelAvatar": "https://yt3.ggpht.com/erBuQrc8PUPxL6UVWNLwUUXZu1QoY1qmWe4x-nVdxhw_kMOeMsT3SDhHM3sYxt2oYKC--zNvug=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/__WfaaAS0O4/hqdefault.jpg",
    "date": "2025-11-21",
    "views": 6730,
    "viewsFormatted": "6.7K"
  },
  {
    "url": "https://www.youtube.com/watch?v=gy-auzoEs-4",
    "title": "Openterface KVM On The uConsole",
    "author": "Jeremiah of All Trades",
    "channelAvatar": "https://yt3.ggpht.com/Kzpe2z08Mo6nKI0B4tLhNCFULkkpGUGFtn5w-P64oHMjjOZxRC25qn7MgVdyiO9Oyl6-bGJX=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/gy-auzoEs-4/hqdefault.jpg",
    "date": "2025-09-10",
    "views": 752,
    "viewsFormatted": "752"
  },
  {
    "url": "https://www.youtube.com/watch?v=UaHBOCbXk1Y",
    "title": "Make your uConsole into a KVM!",
    "author": "Symbiiote",
    "channelAvatar": "https://yt3.ggpht.com/OYi4mIbKHArwGmdur42okpmZ3VMRJlMixLH2YOvgv2EqWzzvxx1wgwh0RugCBjTuYAVGne4B=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/UaHBOCbXk1Y/hqdefault.jpg",
    "date": "2025-08-27",
    "views": 1973,
    "viewsFormatted": "2.0K"
  },
  {
    "url": "https://www.youtube.com/watch?v=VfVGD2bQswQ",
    "title": "A Tiny KVM That Solves Big IT Headaches",
    "author": "Geek Of All Trades",
    "channelAvatar": "https://yt3.ggpht.com/U0OdbO7R13-ySf4G__3r3uQJw3yxAzi4VGjiqaeT5kMOM5VsSB7NRsO_Joks09srZtkwGB5GGFE=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/VfVGD2bQswQ/hqdefault.jpg",
    "date": "2025-06-15",
    "views": 7859,
    "viewsFormatted": "7.9K"
  },
  {
    "url": "https://www.youtube.com/watch?v=xAEQpWyfY-c",
    "title": "This USB KVM Console is Awesome! - Openterface by TechxArtisan",
    "author": "Cameron Gray",
    "channelAvatar": "https://yt3.ggpht.com/5PO3ZYQMljAvN-whnmlMKXvceL0N83EvbrICFDqNT70MgCk_pRAlRAPPE2QZNqsxRfcJ_pRjo7k=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/xAEQpWyfY-c/hqdefault.jpg",
    "date": "2024-03-30",
    "views": 60218,
    "viewsFormatted": "60.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=URAXtrB817E",
    "title": "KVM-GO OpenInterface: Este KVM NO va por red, el KVM que se conecta DIRECTO a tu PC",
    "author": "Javier Gutierrez Abella",
    "channelAvatar": "https://yt3.ggpht.com/ytc/AIdro_lkVDRCHKSbjko5n0Vto1FazyoHLtYHZ0BJLq554iF0ZNW1=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/URAXtrB817E/hqdefault.jpg",
    "date": "2026-03-20",
    "views": 9549,
    "viewsFormatted": "9.5K"
  },
  {
    "url": "https://www.youtube.com/watch?v=JK4XaMo8yEI",
    "title": "A USB KVM with VGA! Openterface KVM-GO Review",
    "author": "apalrd's adventures",
    "channelAvatar": "https://yt3.ggpht.com/qencJ8YC4SCPbV_ylp47d-yNIAMTzt6QlncVrJ8FfwRDYeB4m7St7MZNSCDOVx3Qw_9CJxHR5A=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/JK4XaMo8yEI/hqdefault.jpg",
    "date": "2026-02-26",
    "views": 7828,
    "viewsFormatted": "7.8K"
  },
  {
    "url": "https://www.youtube.com/watch?v=BHRGIE8OGYY",
    "title": "Networkless KVM? Yes please open interface kvm-go",
    "author": "KL Tech Videos",
    "channelAvatar": "https://yt3.ggpht.com/mHmleJwkNJwBHMDRv-JXOxpitAiPG5YIsQ4uDApdTKjWu5mD_sUTfnH8VsL9Zwfcg5PKivTQ7Q=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/BHRGIE8OGYY/hqdefault.jpg",
    "date": "2025-12-31",
    "views": 717,
    "viewsFormatted": "717"
  },
  {
    "url": "https://www.youtube.com/watch?v=d9-i7SYAZr8",
    "title": "The KVM-GO is my new EDC KVM!",
    "author": "Symbiiote",
    "channelAvatar": "https://yt3.ggpht.com/OYi4mIbKHArwGmdur42okpmZ3VMRJlMixLH2YOvgv2EqWzzvxx1wgwh0RugCBjTuYAVGne4B=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/d9-i7SYAZr8/hqdefault.jpg",
    "date": "2025-12-29",
    "views": 1505,
    "viewsFormatted": "1.5K"
  },
  {
    "url": "https://www.youtube.com/watch?v=aXQSNFAFiqk",
    "title": "J’ai testé le KVM le plus compact au monde : OpenTerface KVM Go !",
    "author": "Sam's eXperiments logs",
    "channelAvatar": "https://yt3.ggpht.com/QypC0fMJdJDxdf_04lp6TWkuorFPB9pVZD8oOLwclsvRfJsfzCz01iaSl56A1J9lcCHUHXEM=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/aXQSNFAFiqk/hqdefault.jpg",
    "date": "2025-12-16",
    "views": 357,
    "viewsFormatted": "357"
  },
  {
    "url": "https://www.youtube.com/watch?v=__WfaaAS0O4",
    "title": "OpenInterface Shows New KVM Go at Maker Faire Shenzhen",
    "author": "Electromaker",
    "channelAvatar": "https://yt3.ggpht.com/erBuQrc8PUPxL6UVWNLwUUXZu1QoY1qmWe4x-nVdxhw_kMOeMsT3SDhHM3sYxt2oYKC--zNvug=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/__WfaaAS0O4/hqdefault.jpg",
    "date": "2025-11-21",
    "views": 6730,
    "viewsFormatted": "6.7K"
  },
  {
    "url": "https://www.youtube.com/watch?v=gy-auzoEs-4",
    "title": "Openterface KVM On The uConsole",
    "author": "Jeremiah of All Trades",
    "channelAvatar": "https://yt3.ggpht.com/Kzpe2z08Mo6nKI0B4tLhNCFULkkpGUGFtn5w-P64oHMjjOZxRC25qn7MgVdyiO9Oyl6-bGJX=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/gy-auzoEs-4/hqdefault.jpg",
    "date": "2025-09-10",
    "views": 752,
    "viewsFormatted": "752"
  },
  {
    "url": "https://www.youtube.com/watch?v=UaHBOCbXk1Y",
    "title": "Make your uConsole into a KVM!",
    "author": "Symbiiote",
    "channelAvatar": "https://yt3.ggpht.com/OYi4mIbKHArwGmdur42okpmZ3VMRJlMixLH2YOvgv2EqWzzvxx1wgwh0RugCBjTuYAVGne4B=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/UaHBOCbXk1Y/hqdefault.jpg",
    "date": "2025-08-27",
    "views": 1973,
    "viewsFormatted": "2.0K"
  },
  {
    "url": "https://www.youtube.com/watch?v=VfVGD2bQswQ",
    "title": "A Tiny KVM That Solves Big IT Headaches",
    "author": "Geek Of All Trades",
    "channelAvatar": "https://yt3.ggpht.com/U0OdbO7R13-ySf4G__3r3uQJw3yxAzi4VGjiqaeT5kMOM5VsSB7NRsO_Joks09srZtkwGB5GGFE=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/VfVGD2bQswQ/hqdefault.jpg",
    "date": "2025-06-15",
    "views": 7859,
    "viewsFormatted": "7.9K"
  },
  {
    "url": "https://www.youtube.com/watch?v=xAEQpWyfY-c",
    "title": "This USB KVM Console is Awesome! - Openterface by TechxArtisan",
    "author": "Cameron Gray",
    "channelAvatar": "https://yt3.ggpht.com/5PO3ZYQMljAvN-whnmlMKXvceL0N83EvbrICFDqNT70MgCk_pRAlRAPPE2QZNqsxRfcJ_pRjo7k=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/xAEQpWyfY-c/hqdefault.jpg",
    "date": "2024-03-30",
    "views": 60218,
    "viewsFormatted": "60.2K"
  }
] as HomeVideo[];
