// AUTO-GENERATED by scripts/sync-home-videos.mjs — do not edit manually
// locale: zh | generated: 2026-08-06T03:16:23.440Z

import type { HomeVideo } from '../lib/youtube';

export const homeVideosLocale = 'zh' as const;

/** Top 10 videos for homepage strip (duplicated for seamless scroll). */
export const homeVideos: HomeVideo[] = [
  {
    "url": "https://www.youtube.com/watch?v=nl24-rPjOr8",
    "title": "Beta Testing The Openterface Keymod #keymod #openterface",
    "author": "Valleytech Custom Solutions",
    "channelAvatar": "https://yt3.ggpht.com/ZBz7pGNOU1PD-u6cEKWT6q0GKeep5Gh1pTHprSKHQhmHTZQGba71IoCUkQGrzwZSNW2rt8DMQg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/nl24-rPjOr8/hqdefault.jpg",
    "date": "2026-06-05",
    "views": 19232,
    "viewsFormatted": "19.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=uq0F1VKmQdU",
    "title": "USB KVM that You Can Put on a Keychain | Openterface KVM-GO",
    "author": "Home Network Guy",
    "channelAvatar": "https://yt3.ggpht.com/wmQPGuau8ThNtsGR0Kc6m78_55P0_hH6fB4p2dPwHlIXyZ61SGk7yl9ogIMxaWhb8Q0f8zAn=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/uq0F1VKmQdU/hqdefault.jpg",
    "date": "2026-06-06",
    "views": 1875,
    "viewsFormatted": "1.9K"
  },
  {
    "url": "https://www.youtube.com/watch?v=x35Qs89WP_g",
    "title": "Openterface Keymod - Control Any Device with Your Phone",
    "author": "Valleytech Custom Solutions",
    "channelAvatar": "https://yt3.ggpht.com/ZBz7pGNOU1PD-u6cEKWT6q0GKeep5Gh1pTHprSKHQhmHTZQGba71IoCUkQGrzwZSNW2rt8DMQg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/x35Qs89WP_g/hqdefault.jpg",
    "date": "2026-07-13",
    "views": 3222,
    "viewsFormatted": "3.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=OpERf1UFToQ",
    "title": "I can set up a computer without touching it",
    "author": "Level 2 Jeff",
    "channelAvatar": "https://yt3.ggpht.com/6Pcr9KpMMJay2uNTldCH_RH62dJLKvdvZH5_5hTCzImkO8lQg5ctYymsZ9ODb__yA3Nwg36rAg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/OpERf1UFToQ/hqdefault.jpg",
    "date": "2026-08-03",
    "views": 26196,
    "viewsFormatted": "26.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=URAXtrB817E",
    "title": "KVM-GO OpenInterface: Este KVM NO va por red, el KVM que se conecta DIRECTO a tu PC",
    "author": "Javier Gutierrez Abella",
    "channelAvatar": "https://yt3.ggpht.com/ytc/AIdro_lkVDRCHKSbjko5n0Vto1FazyoHLtYHZ0BJLq554iF0ZNW1=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/URAXtrB817E/hqdefault.jpg",
    "date": "2026-03-20",
    "views": 9549,
    "viewsFormatted": "9.5K"
  },
  {
    "url": "https://www.youtube.com/watch?v=JK4XaMo8yEI",
    "title": "A USB KVM with VGA! Openterface KVM-GO Review",
    "author": "apalrd's adventures",
    "channelAvatar": "https://yt3.ggpht.com/qencJ8YC4SCPbV_ylp47d-yNIAMTzt6QlncVrJ8FfwRDYeB4m7St7MZNSCDOVx3Qw_9CJxHR5A=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/JK4XaMo8yEI/hqdefault.jpg",
    "date": "2026-02-26",
    "views": 7828,
    "viewsFormatted": "7.8K"
  },
  {
    "url": "https://www.youtube.com/watch?v=BHRGIE8OGYY",
    "title": "Networkless KVM? Yes please open interface kvm-go",
    "author": "KL Tech Videos",
    "channelAvatar": "https://yt3.ggpht.com/mHmleJwkNJwBHMDRv-JXOxpitAiPG5YIsQ4uDApdTKjWu5mD_sUTfnH8VsL9Zwfcg5PKivTQ7Q=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/BHRGIE8OGYY/hqdefault.jpg",
    "date": "2025-12-31",
    "views": 717,
    "viewsFormatted": "717"
  },
  {
    "url": "https://www.youtube.com/watch?v=d9-i7SYAZr8",
    "title": "The KVM-GO is my new EDC KVM!",
    "author": "Symbiiote",
    "channelAvatar": "https://yt3.ggpht.com/OYi4mIbKHArwGmdur42okpmZ3VMRJlMixLH2YOvgv2EqWzzvxx1wgwh0RugCBjTuYAVGne4B=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/d9-i7SYAZr8/hqdefault.jpg",
    "date": "2025-12-29",
    "views": 1505,
    "viewsFormatted": "1.5K"
  },
  {
    "url": "https://www.youtube.com/watch?v=aXQSNFAFiqk",
    "title": "J’ai testé le KVM le plus compact au monde : OpenTerface KVM Go !",
    "author": "Sam's eXperiments logs",
    "channelAvatar": "https://yt3.ggpht.com/QypC0fMJdJDxdf_04lp6TWkuorFPB9pVZD8oOLwclsvRfJsfzCz01iaSl56A1J9lcCHUHXEM=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/aXQSNFAFiqk/hqdefault.jpg",
    "date": "2025-12-16",
    "views": 357,
    "viewsFormatted": "357"
  },
  {
    "url": "https://www.youtube.com/watch?v=__WfaaAS0O4",
    "title": "OpenInterface Shows New KVM Go at Maker Faire Shenzhen",
    "author": "Electromaker",
    "channelAvatar": "https://yt3.ggpht.com/erBuQrc8PUPxL6UVWNLwUUXZu1QoY1qmWe4x-nVdxhw_kMOeMsT3SDhHM3sYxt2oYKC--zNvug=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/__WfaaAS0O4/hqdefault.jpg",
    "date": "2025-11-21",
    "views": 6730,
    "viewsFormatted": "6.7K"
  },
  {
    "url": "https://www.youtube.com/watch?v=nl24-rPjOr8",
    "title": "Beta Testing The Openterface Keymod #keymod #openterface",
    "author": "Valleytech Custom Solutions",
    "channelAvatar": "https://yt3.ggpht.com/ZBz7pGNOU1PD-u6cEKWT6q0GKeep5Gh1pTHprSKHQhmHTZQGba71IoCUkQGrzwZSNW2rt8DMQg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/nl24-rPjOr8/hqdefault.jpg",
    "date": "2026-06-05",
    "views": 19232,
    "viewsFormatted": "19.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=uq0F1VKmQdU",
    "title": "USB KVM that You Can Put on a Keychain | Openterface KVM-GO",
    "author": "Home Network Guy",
    "channelAvatar": "https://yt3.ggpht.com/wmQPGuau8ThNtsGR0Kc6m78_55P0_hH6fB4p2dPwHlIXyZ61SGk7yl9ogIMxaWhb8Q0f8zAn=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/uq0F1VKmQdU/hqdefault.jpg",
    "date": "2026-06-06",
    "views": 1875,
    "viewsFormatted": "1.9K"
  },
  {
    "url": "https://www.youtube.com/watch?v=x35Qs89WP_g",
    "title": "Openterface Keymod - Control Any Device with Your Phone",
    "author": "Valleytech Custom Solutions",
    "channelAvatar": "https://yt3.ggpht.com/ZBz7pGNOU1PD-u6cEKWT6q0GKeep5Gh1pTHprSKHQhmHTZQGba71IoCUkQGrzwZSNW2rt8DMQg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/x35Qs89WP_g/hqdefault.jpg",
    "date": "2026-07-13",
    "views": 3222,
    "viewsFormatted": "3.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=OpERf1UFToQ",
    "title": "I can set up a computer without touching it",
    "author": "Level 2 Jeff",
    "channelAvatar": "https://yt3.ggpht.com/6Pcr9KpMMJay2uNTldCH_RH62dJLKvdvZH5_5hTCzImkO8lQg5ctYymsZ9ODb__yA3Nwg36rAg=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/OpERf1UFToQ/hqdefault.jpg",
    "date": "2026-08-03",
    "views": 26196,
    "viewsFormatted": "26.2K"
  },
  {
    "url": "https://www.youtube.com/watch?v=URAXtrB817E",
    "title": "KVM-GO OpenInterface: Este KVM NO va por red, el KVM que se conecta DIRECTO a tu PC",
    "author": "Javier Gutierrez Abella",
    "channelAvatar": "https://yt3.ggpht.com/ytc/AIdro_lkVDRCHKSbjko5n0Vto1FazyoHLtYHZ0BJLq554iF0ZNW1=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/URAXtrB817E/hqdefault.jpg",
    "date": "2026-03-20",
    "views": 9549,
    "viewsFormatted": "9.5K"
  },
  {
    "url": "https://www.youtube.com/watch?v=JK4XaMo8yEI",
    "title": "A USB KVM with VGA! Openterface KVM-GO Review",
    "author": "apalrd's adventures",
    "channelAvatar": "https://yt3.ggpht.com/qencJ8YC4SCPbV_ylp47d-yNIAMTzt6QlncVrJ8FfwRDYeB4m7St7MZNSCDOVx3Qw_9CJxHR5A=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/JK4XaMo8yEI/hqdefault.jpg",
    "date": "2026-02-26",
    "views": 7828,
    "viewsFormatted": "7.8K"
  },
  {
    "url": "https://www.youtube.com/watch?v=BHRGIE8OGYY",
    "title": "Networkless KVM? Yes please open interface kvm-go",
    "author": "KL Tech Videos",
    "channelAvatar": "https://yt3.ggpht.com/mHmleJwkNJwBHMDRv-JXOxpitAiPG5YIsQ4uDApdTKjWu5mD_sUTfnH8VsL9Zwfcg5PKivTQ7Q=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/BHRGIE8OGYY/hqdefault.jpg",
    "date": "2025-12-31",
    "views": 717,
    "viewsFormatted": "717"
  },
  {
    "url": "https://www.youtube.com/watch?v=d9-i7SYAZr8",
    "title": "The KVM-GO is my new EDC KVM!",
    "author": "Symbiiote",
    "channelAvatar": "https://yt3.ggpht.com/OYi4mIbKHArwGmdur42okpmZ3VMRJlMixLH2YOvgv2EqWzzvxx1wgwh0RugCBjTuYAVGne4B=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/d9-i7SYAZr8/hqdefault.jpg",
    "date": "2025-12-29",
    "views": 1505,
    "viewsFormatted": "1.5K"
  },
  {
    "url": "https://www.youtube.com/watch?v=aXQSNFAFiqk",
    "title": "J’ai testé le KVM le plus compact au monde : OpenTerface KVM Go !",
    "author": "Sam's eXperiments logs",
    "channelAvatar": "https://yt3.ggpht.com/QypC0fMJdJDxdf_04lp6TWkuorFPB9pVZD8oOLwclsvRfJsfzCz01iaSl56A1J9lcCHUHXEM=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/aXQSNFAFiqk/hqdefault.jpg",
    "date": "2025-12-16",
    "views": 357,
    "viewsFormatted": "357"
  },
  {
    "url": "https://www.youtube.com/watch?v=__WfaaAS0O4",
    "title": "OpenInterface Shows New KVM Go at Maker Faire Shenzhen",
    "author": "Electromaker",
    "channelAvatar": "https://yt3.ggpht.com/erBuQrc8PUPxL6UVWNLwUUXZu1QoY1qmWe4x-nVdxhw_kMOeMsT3SDhHM3sYxt2oYKC--zNvug=s88-c-k-c0x00ffffff-no-rj",
    "thumbnail": "https://i.ytimg.com/vi/__WfaaAS0O4/hqdefault.jpg",
    "date": "2025-11-21",
    "views": 6730,
    "viewsFormatted": "6.7K"
  }
] as HomeVideo[];
